[package]
name = "bevy_mesh_decal"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16"

[dev-dependencies]

bevy_rapier3d = { git = "https://github.com/mnmaita/bevy_rapier.git", branch = "mnmaita/bevy-0.16", features = [
    "simd-stable",
    "debug-render-3d",
] }
bevy_fps_controller = { git = "https://github.com/qhdwight/bevy_fps_controller", branch = "development" }
